version: '3.4'

services:
  catalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8000:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - car-rental

  sql-server:
    ports:
        - 1434:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=12345nikitaN
        - MSSQL_PID=Express
    volumes:
        - sql-server-vol:/var/opt/mssql
    networks:
        - car-rental

  elasticsearch:
    ports:
      - 9200:9200
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    networks:
      - car-rental

  kibana:
    ports:
      - 5601:5601
    environment:
        - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - car-rental
      
networks:
  car-rental:
    name: car-rental
    driver: bridge

volumes:
  elasticsearch-data:
  sql-server-vol: