version: '3.4'

services:
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: CatalogApi/Dockerfile
    depends_on:
       - sql-server
    
  sql-server:
     container_name: sql-server
     image: mcr.microsoft.com/mssql/server:2019-latest

  elasticsearch:
     container_name: elasticsearch
     image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
     
  kibana:
     container_name: kibana
     image: docker.elastic.co/kibana/kibana:7.17.0
     depends_on:
        - elasticsearch